language: node_js

services:
  - docker

node_js:
  - "8"
  - "11"

before_script:
  - set -o pipefail
  - npm install
  - npm install codecov -g

script:
  - npm run build
  - npm run lint
  - npm run docker:test
  - codecov -f coverage/*.json
