version: '3.3'

services:
  underbase-dev:
    image: node:8-alpine
    command: sh -c 'cd /usr/src/underbase && exec npm test'
    depends_on:
      - underbase-db
    environment:
      - 'DBURL=mongodb://underbase-db:27017/underbase-db'
      - 'NODE_ENV=developoment'
    volumes:
      - '.:/usr/src/underbase'
    ports:
      # Warning: Binding to 0.0.0.0 without firewall protection opens
      # host up to outside access. Make sure to turn on firewall
      # if you are not testing from an exernal machine or device.
      - "0.0.0.0:5857-5870:5857-5870"

  underbase-db:
    image: mongo:latest
    ports:
      - "27019:27017"
    command: mongod --bind_ip 0.0.0.0 --smallfiles

  underbase-test:
    image: node:8-alpine
    command: sh -c 'cd /usr/src/underbase && exec npm test'
    depends_on:
      - underbase-db
    environment:
      - 'DBURL=mongodb://underbase-db:27017/underbase-db'
      - 'NODE_ENV=test'
    volumes:
      - '.:/usr/src/underbase'

