version: '3.3'

services:
  metro-dev:
    image: node:8-alpine
    command: sh -c 'cd /usr/src/metro && exec npm test'
    depends_on:
      - metro-db
    environment:
      - 'DBURL=mongodb://metro-db:27017/metro-db'
      - 'NODE_ENV=developoment'
    volumes:
      - '.:/usr/src/metro'
    ports:
      # Warning: Binding to 0.0.0.0 without firewall protection opens
      # host up to outside access. Make sure to turn on firewall
      # if you are not testing from an exernal machine or device.
      - "0.0.0.0:5857-5870:5857-5870"

  metro-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0 --smallfiles

  metro-test:
    image: node:8-alpine
    command: sh -c 'cd /usr/src/metro && exec npm test'
    depends_on:
      - metro-db
    environment:
      - 'DBURL=mongodb://metro-db:27017/metro-db'
      - 'NODE_ENV=test'
    volumes:
      - '.:/usr/src/metro'

