version: 2.0
jobs:
 build:
   docker:
     - image: node:8
   steps:
     - run:
         name: Installation
         command: npm install
     - run:
         name: Build
         command: npm run build
     - run:
         name: Lint
         command: npm run lint
     - run:
         name: Test
         command: bash ./test.sh
